{
#  "UserPortImap":     "1143",
#  "UserPortSmtp":     "1025",
#  "AllowProxy":       "false",
#  "CacheEnabled":     "true",
#  "CacheCompression": "true",
#  "CacheDir":         "/var/cache/peroxide/cache",
#  "X509Key":          "/etc/peroxide/key.pem",
#  "X509Cert":         "/etc/peroxide/cert.pem",
#  "CookieJar":        "/var/lib/peroxide/cookies.json",
#  "CredentialsStore": "/var/lib/peroxide/credentials.json",
#  "ServerAddress":    "[::0]",
#  "BCCSelf":          "false"
}
